JNG-4540 Release osgi-utils
BlackBeltTechnology/osgi-utils pull request #51
Opened 2023-03-05 20:50 UTC by gaborflorian

2023-03-06 10:18 UTC, bencegelei requested changes

2023-03-06 10:18 UTC, bencegelei commented on pom.xml
> +        <surefire-version>3.0.0-M5</surefire-version>
Version downgrade?

2023-03-06 13:30 UTC, gaborflorian commented on pom.xml
> +        <surefire-version>3.0.0-M5</surefire-version>
Something wrong with the surefire plugin

2023-03-06 13:39 UTC, bencegelei approved these changes

2023-03-06 13:51 UTC, bencegelei approved these changes

2023-03-07 14:38 UTC, noherczeg requested changes

2023-03-07 14:38 UTC, noherczeg commented on pom.xml
> +        <surefire-version>3.0.0-M5</surefire-version>
Should be M7

2023-03-07 16:18 UTC, gaborflorian commented on pom.xml
> +        <surefire-version>3.0.0-M5</surefire-version>
[1d7f0ba](https://github.com/BlackBeltTechnology/osgi-utils/pull/51/commits/1d7f0ba2ea41d5c3a8b9150dbba80826e7f89443)

2023-03-07 16:44 UTC, noherczeg approved these changes

2023-03-08 07:55 UTC, robertcsakany requested changes

2023-03-08 07:55 UTC, robertcsakany commented on pom.xml
> -
Why sonar is removed? I haven't seen sonar definition at all.

2023-03-08 08:46 UTC, gaborflorian commented on pom.xml
> -
duplicated plugin

2023-03-08 11:33 UTC, Madmat8 approved these changes

2023-03-08 11:52 UTC, robertcsakany approved these changes

2023-03-09 12:20 UTC, merged